name: 'Build Go from source on Windows'
description: 'Build and test Go from source code on Windows'
inputs:
  go_variables:
    description: 'Variables and their values ready for export'
    required: false
  test_build:
    description: 'When set to true, all tests of build are executed'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Clone master of go
      shell: powershell
      run: |
        git clone --depth=1 --branch master --single-branch --no-tags https://go.googlesource.com/go

    - name: Apply patch files
      shell: powershell
      run: |
        if (!(Test-Path *.patch -PathType leaf)) { echo "No patch file found. Skipping."; exit 0; }
        move *.patch .\go\src\
        cd go/src
        git config user.email "${{ github.event.pusher.email }}"
        git config user.name "${{ github.event.pusher.name }}"
        git am --ignore-space-change --ignore-whitespace --whitespace=fix $(dir *.patch).Name
        git show --stat -n $(Get-ChildItem *.patch).Count
        del .\*.patch

    - name: Build
      shell: powershell
      run: |
        ${{ inputs.go_variables }}
        $Env:GOOS = If ((Test-Path variable:GOOS)) { $GOOS } else { go env GOOS; $GOOS = go env GOOS }
        go env -w GOOS=$GOOS
        $Env:GOARCH = If ((Test-Path variable:GOARCH)) { $GOARCH } else { go env GOARCH; $GOARCH = go env GOARCH }
        go env -w GOARCH=$GOARCH
        echo "goos=$GOOS" >> $env:GITHUB_ENV
        echo "goarch=$GOARCH" >> $env:GITHUB_ENV
        If (!(Test-Path variable:GOROOT_BOOTSTRAP)) { $GOROOT_BOOTSTRAP = "$(go env GOROOT)" }
        $crosscompile = 'true'
        if (($GOOS -eq $(go env GOHOSTOS)) -and ($GOARCH -eq $(go env GOHOSTARCH))) { $crosscompile = 'false' }
        echo "crosscompile=$crosscompile" >> $env:GITHUB_ENV
        cd go/src
        .\make.bat --no-banner --no-local

    - name: Test locally
      shell: powershell
      if: ${{ inputs.test_build == 'true' && env.crosscompile == 'false' }}
      run: |
        cd go/src
        .\run.bat --no-rebuild  --no-local

    - name: Test cross-compile
      shell: powershell
      if: ${{ inputs.test_build == 'true' && env.crosscompile == 'true' }}
      run: |
        echo "Testing a cross-compiled version of Go on windows is not implemented for now"

branding:
  icon: crosshair
  color: blue
