name: 'Build Go from source on Windows'
description: 'build and test go on tip using Windows'

runs:
  using: "composite"
  steps:
    - name: Clone master of go
      shell: bash
      run: |
        git clone --depth=1 --branch master --single-branch --no-tags https://go.googlesource.com/go

    - name: Build
      shell: bash
      run: |
        cd go/src
        $GOROOT_BOOTSTRAP = go env GOROOT
        .\all.bat
        ..\bin\go.exe version

branding:
  icon: crosshair
  color: blue
