name: dragonfly
on:
  push:
    branches:
      - 'master'
    paths:
      - 'action.yml'
      - '.github/workflows/dragonfly.yml'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
      id: go

    - name: Build go from tip
      uses: iwdgo/gotip-build@updates
      id: gotip
      with:
        go_variables: GO_TEST_SHORT=1 GO_TEST_TIMEOUT_SCALE=8 GOOS=dragonfly GOARCH=amd64
        test_build: true
