name: arm v6/v7
on:
  push:
    branches:
      - 'master'
    paths:
      - 'action.yml'
jobs:

  build:
    strategy:
      matrix:
        go_arch: [arm]
        go_arm: [6, 7]
      fail-fast: false
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17.x
      id: go

    - name: Build go from tip
      uses: iwdgo/gotip-build@add-v7-v6
      id: gotip
      with:
        go_variables: CGO_ENABLED=0 GOARCH=${{ matrix.go_arch }} GOARM=${{ matrix.go_arm}} GOROOT_FINAL=/
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'false' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/

    - name: Upload go executable
      uses: actions/upload-artifact@v3
      if: ${{ env.crosscompile == 'true' }}
      with:
        name: gotip-${{ env.goos }}-${{ env.goarch }}
        path: go/bin/${{ env.goos }}_${{ env.goarch }}
