name: windows
on:
  push:
    branches:
      - 'master-windows'
    paths:
      - 'action.yml'
      - '.github/workflows/windows_test.yml'
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
      id: go

    - name: Build go from tip
      uses: iwdgo/gotip-build@master-windows
      id: gotip
      with:
        test_build: true

    - name: Upload go executable
      uses: actions/upload-artifact@v4
      with:
        name: gotip-${{ runner.os }}-${{ runner.arch }}
        path: .\go
